### ISSUE TITLE
Why do I need to run the following code every time before running the main file?

### ISSUE THREAD

**Issue by luckybabei** [f4nku4n/IMS-LOMONAS#1]
Why do I need to run the following code every time before running the main file?

“from evoxbench.database.init import config

config('database', 'data')”

**Comment by f4nku4n** [comment]
Running these lines allows you to load the CEC'2023 databases (you can see more [here](https://github.com/EMI-Group/evoxbench)). Actually, you only just need to run these lines once (before running the main file). However, to make sure that we always can load the databases, I suggest executing them every time whenever we run the main file.

**Comment by luckybabei** [comment]
Sorry to bother you again, I encountered a new problem. When the algorithm is set to "lomonas" and the problem is set to "gecco", the following error occurs. How to solve it?

Auto Configuration Succeed!, Using database database.
Auto Configuration Succeed!, Using database database.
Configuration Succeed!
  0%|          | 0/31 [00:00<?, ?it/s]04/29 03:44:11 PM Run: 1
  0%|          | 0/31 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/NAS/IMS-LOMONAS/main.py", line 170, in <module>
    main(args)
  File "/home/NAS/IMS-LOMONAS/main.py", line 75, in main
    search_cost = algo.problem.benchmark.evaluator.search_cost
AttributeError: 'MacroNASEvaluator' object has no attribute 'search_cost'

**Comment by f4nku4n** [comment]
Sorry for my mistake. You can fix this problem by adding:
"self.search_cost = 0.0
  self.evaluation_cost = 0.0"
to the **MacroNASSearchSpace** object (_\_\_init___ function) in the [macroNAS.py](https://github.com/f4nku4n/IMS-LOMONAS/blob/master/test_suites/macroNAS/macroNAS.py).

Btw, we note that the authors of the [MacroNAS search space](https://github.com/ArkadiyD/MacroNASBenchmark) do not provide the cost of training architectures. As a result, the search/evaluation costs when experimenting on MacroNAS are thus 0.0 seconds.

**Comment by luckybabei** [comment]
Thank you for your patience. The issue has been resolved, and it works now.
